service: lamda-practice
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

functions:
  SES:
    handler: handler.SES
    timeout: 30
    memorySize: 128
    events:
      - httpApi:
          path: /
          method: get
          # cors: true
  roundTwo:
    handler: handler.roundTwo
    events:
      - httpApi:
          path: /roundTwo
          method: get
