service: email-service
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-1

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

functions:
  simpleEmail:
    handler: handler.simpleEmail
    events:
      - httpApi:
          path: /
          method: get
  # roundTwo:
  #   handler: handler.roundTwo
  #   events:
  #     - httpApi:
  #         path: /roundTwo
  #         method: get
